from django.db import models

class Bok(models.Model):
    bk_id = models.CharField(max_length=15)
    pr_id = models.CharField(max_length=10)
    p_nr_fab = models.CharField(max_length=20)
    u_id = models.CharField(max_length=7)
    u_data_p = models.CharField(max_length=10)
    u_nr_potp = models.CharField(max_length=20)
    u_dost = models.CharField(max_length=50)
    u_cecha_p = models.CharField(max_length=1)
    u_stan_tp = models.CharField(max_length=1)
    u_podstawa = models.CharField(max_length=2)
    p_komplet = models.CharField(max_length=255)
    k_do_k_n = models.CharField(max_length=1)
    k_do_data = models.CharField(max_length=10)
    k_do_pesel = models.CharField(max_length=11)
    k_do_pin = models.CharField(max_length=4)
    k_do_datap = models.CharField(max_length=10)
    k_pr_sp_nr = models.CharField(max_length=15)
    k_sk_do = models.CharField(max_length=1)
    k_bk_data = models.CharField(max_length=10)
    k_bk_pesel = models.CharField(max_length=11)
    k_bk_pin = models.CharField(max_length=4)
    k_pr_sp = models.CharField(max_length=255)
    k_form = models.CharField(max_length=255)
    bk_uwagi = models.CharField(max_length=1)
    u_data_w = models.CharField(max_length=10)
    u_nr_potw = models.CharField(max_length=20)
    u_odbior = models.CharField(max_length=50)
    u_nr_up = models.CharField(max_length=10)
    bk_kbok = models.CharField(max_length=50)
    om_pracow = models.CharField(max_length=3)
    p_ind_rek = models.CharField(max_length=17)
    p_typ = models.CharField(max_length=50)
    u_nazwa_s = models.CharField(max_length=12)
    kod_ean8 = models.CharField(max_length=8)
    u_kal = models.CharField(max_length=1)
    gwar = models.CharField(max_length=1)
    indeks = models.CharField(max_length=11)
    denp = models.CharField(max_length=1)
    cecha_br = models.CharField(max_length=1)
    paczka = models.CharField(max_length=1)

class Bok_arch(models.Model):
    bk_id = models.CharField(max_length=15)
    pr_id = models.CharField(max_length=10)
    p_nr_fab = models.CharField(max_length=20)
    u_id = models.CharField(max_length=7)
    u_data_p = models.CharField(max_length=10)
    u_nr_potp = models.CharField(max_length=20)
    u_dost = models.CharField(max_length=50)
    u_cecha_p = models.CharField(max_length=1)
    u_stan_tp = models.CharField(max_length=1)
    u_podstawa = models.CharField(max_length=2)
    p_komplet = models.CharField(max_length=255)
    k_do_k_n = models.CharField(max_length=1)
    k_do_data = models.CharField(max_length=10)
    k_do_pesel = models.CharField(max_length=11)
    k_do_pin = models.CharField(max_length=4)
    k_do_datap = models.CharField(max_length=10)
    k_pr_sp_nr = models.CharField(max_length=15)
    k_sk_do = models.CharField(max_length=1)
    k_bk_data = models.CharField(max_length=10)
    k_bk_pesel = models.CharField(max_length=11)
    k_bk_pin = models.CharField(max_length=4)
    k_pr_sp = models.CharField(max_length=255)
    k_form = models.CharField(max_length=255)
    bk_uwagi = models.CharField(max_length=1)
    u_data_w = models.CharField(max_length=10)
    u_nr_potw = models.CharField(max_length=20)
    u_odbior = models.CharField(max_length=50)
    u_nr_up = models.CharField(max_length=10)
    bk_kbok = models.CharField(max_length=50)
    om_pracow = models.CharField(max_length=3)
    p_ind_rek = models.CharField(max_length=17)
    p_typ = models.CharField(max_length=50)
    u_nazwa_s = models.CharField(max_length=12)
    kod_ean8 = models.CharField(max_length=8)
    indeks = models.CharField(max_length=11)
    denp = models.CharField(max_length=1)
    cecha_br = models.CharField(max_length=1)
    paczka = models.CharField(max_length=1)

class Bok_dep(models.Model):
    bk_id = models.CharField(max_length=15)
    gr_id = models.CharField(max_length=11)
    p_nr_fab = models.CharField(max_length=20)
    u_id = models.CharField(max_length=7)
    u_data_p = models.CharField(max_length=10)
    u_nr_potp = models.CharField(max_length=20)
    u_dost = models.CharField(max_length=50)
    u_cecha_p = models.CharField(max_length=1)
    u_stan_tp = models.CharField(max_length=1)
    u_podstawa = models.CharField(max_length=2)
    p_komplet = models.CharField(max_length=255)
    u_data_w = models.CharField(max_length=10)
    u_nr_potw = models.CharField(max_length=20)
    k_pr_sp = models.CharField(max_length=255)
    u_odbior = models.CharField(max_length=50)
    u_nr_up = models.CharField(max_length=10)
    bk_kbok = models.CharField(max_length=50)
    p_ind_rek = models.CharField(max_length=17)
    p_typ = models.CharField(max_length=50)
    u_nazwa_s = models.CharField(max_length=12)
    kod_ean8 = models.CharField(max_length=8)
    m_dostawy = models.CharField(max_length=12)
    c_dostawy = models.CharField(max_length=20)
    indeks = models.CharField(max_length=11)
    denp = models.CharField(max_length=1)
    cecha_br = models.CharField(max_length=1)
    paczka = models.CharField(max_length=1)

class Bok_dep_arch(models.Model):
    bk_id = models.CharField(max_length=15)
    gr_id = models.CharField(max_length=11)
    p_nr_fab = models.CharField(max_length=20)
    u_id = models.CharField(max_length=7)
    u_data_p = models.CharField(max_length=10)
    u_nr_potp = models.CharField(max_length=20)
    u_dost = models.CharField(max_length=50)
    u_cecha_p = models.CharField(max_length=1)
    u_stan_tp = models.CharField(max_length=1)
    u_podstawa = models.CharField(max_length=2)
    p_komplet = models.CharField(max_length=255)
    u_data_w = models.CharField(max_length=10)
    u_nr_potw = models.CharField(max_length=20)
    k_pr_sp = models.CharField(max_length=255)
    u_odbior = models.CharField(max_length=50)
    u_nr_up = models.CharField(max_length=10)
    bk_kbok = models.CharField(max_length=50)
    p_ind_rek = models.CharField(max_length=17)
    p_typ = models.CharField(max_length=50)
    u_nazwa_s = models.CharField(max_length=12)
    kod_ean8 = models.CharField(max_length=8)
    m_dostawy = models.CharField(max_length=12)
    c_dostawy = models.CharField(max_length=20)
    indeks = models.CharField(max_length=11)
    denp = models.CharField(max_length=1)
    cecha_br = models.CharField(max_length=1)
    paczka = models.CharField(max_length=1)

class Bok_koszykp(models.Model):
    koszyk_nr = models.CharField(max_length=4)
    p_nr_fab = models.CharField(max_length=20)
    p_typ = models.CharField(max_length=50)
    uzytkownik = models.CharField(max_length=12)
    ind_rek = models.CharField(max_length=17)
    ko_data = models.CharField(max_length=10)
    akcept = models.CharField(max_length=1)
    podstawa = models.CharField(max_length=30)

class Dep_pacz(models.Model):
    bk_id = models.CharField(max_length=15)
    nr_paczki = models.CharField(max_length=20)
    paczka_do = models.CharField(max_length=12)
    paczka_pop = models.CharField(max_length=12)
    dp_rejon = models.CharField(max_length=6)
    p_komplet = models.CharField(max_length=255)
    miej_dep = models.CharField(max_length=30)
    plomba = models.CharField(max_length=1)
    nr_plomby = models.CharField(max_length=20)
    dp_datap = models.CharField(max_length=10)
    dp_dost = models.CharField(max_length=50)
    dp_potwp = models.CharField(max_length=20)
    dp_kbok = models.CharField(max_length=50)
    dp_dataw = models.CharField(max_length=10)
    dp_odbor = models.CharField(max_length=50)
    dp_nr_up = models.CharField(max_length=10)
    dp_kbokw = models.CharField(max_length=50)
    dp_potww = models.CharField(max_length=20)
    dp_wydana = models.CharField(max_length=1)

class Doplan_arch(models.Model):
    p_nr_fab = models.CharField(max_length=20)
    p_typ = models.CharField(max_length=50)
    kod_ean8 = models.CharField(max_length=8)
    uzytkownik = models.CharField(max_length=12)
    podstawa = models.CharField(max_length=30)
    ko_data = models.CharField(max_length=10)
    zapisal = models.CharField(max_length=30)
    k_data_pl = models.CharField(max_length=10)
    k_data_pl1 = models.CharField(max_length=10)
    k_data_pl2 = models.CharField(max_length=10)
    k_data_pl3 = models.CharField(max_length=10)
    k_data_pl4 = models.CharField(max_length=10)
    pr_id = models.CharField(max_length=10)
    ind_rek = models.CharField(max_length=17)

class Foxuser(models.Model):
    type = models.CharField(max_length=12)
    id = models.CharField(max_length=12)
    name = models.CharField(max_length=255)
    readonly = models.CharField(max_length=1)
    ckval = models.CharField(max_length=6)
    data = models.CharField(max_length=255)
    updated = models.CharField(max_length=10)

class Grupa_me(models.Model):
    gr_id = models.CharField(max_length=2)
    gr_nazwa = models.CharField(max_length=70)
    ind_rek = models.CharField(max_length=17)

class Gr_id_indeks(models.Model):
    gr_id = models.CharField(max_length=11)
    indeks = models.CharField(max_length=11)

class Import_zm(models.Model):
    dnia = models.CharField(max_length=19)
    gr_id = models.CharField(max_length=11)
    p_typ = models.CharField(max_length=50)
    p_nr_fab = models.CharField(max_length=20)
    gr_idn = models.CharField(max_length=11)
    p_typn = models.CharField(max_length=50)



class Ind_rek_del(models.Model):
    ind_rek = models.CharField(max_length=17)
    ind_tab = models.CharField(max_length=2)
    ind_poczta = models.CharField(max_length=50)

class Ind_rek_zm(models.Model):
    ind_rek = models.CharField(max_length=17)
    p_nr_fab = models.CharField(max_length=20)
    gr_id = models.CharField(max_length=11)
    u_id = models.CharField(max_length=7)
    ind_poczta = models.CharField(max_length=50)
    ind4_old = models.CharField(max_length=11)
    ind4 = models.CharField(max_length=11)

class Karta_br_cz(models.Model):
    gr_id = models.CharField(max_length=11)
    p_nr_fab = models.CharField(max_length=20)
    k_pr_sp_nr = models.CharField(max_length=15)
    kp_nr = models.CharField(max_length=16)
    om_id = models.CharField(max_length=7)
    m_nazwa = models.CharField(max_length=40)
    m_indeks = models.CharField(max_length=10)
    m_jm = models.CharField(max_length=5)
    m_stan = models.CharField(max_length=10)
    p_ind_rek = models.CharField(max_length=17)

class Karta_mag_st(models.Model):
    m_nr = models.CharField(max_length=7)
    om_id = models.CharField(max_length=8)
    m_nazwa = models.CharField(max_length=40)
    m_indeks = models.CharField(max_length=10)
    m_nr_katal = models.CharField(max_length=15)
    m_kar = models.CharField(max_length=1)
    m_jm = models.CharField(max_length=5)
    m_cena = models.CharField(max_length=10)
    m_stan = models.CharField(max_length=10)
    m_norma_a = models.CharField(max_length=15)
    m_norma_b = models.CharField(max_length=15)
    m_nr_reg = models.CharField(max_length=20)
    m_stan_kr = models.CharField(max_length=10)
    m_druk = models.CharField(max_length=1)

class Karta_mag_zm(models.Model):
    m_nr = models.CharField(max_length=7)
    om_id = models.CharField(max_length=8)
    m_data = models.CharField(max_length=19)
    l_nazw_imi = models.CharField(max_length=30)
    m_faktura = models.CharField(max_length=50)
    m_przychod = models.CharField(max_length=10)
    m_rozchod = models.CharField(max_length=10)
    m_stan = models.CharField(max_length=10)

class Karta_pr_mat(models.Model):
    k_pr_sp_nr = models.CharField(max_length=15)
    m_om_nr = models.CharField(max_length=15)
    kp_ile_zap = models.CharField(max_length=10)
    kp_nazw_kp = models.CharField(max_length=30)
    kp_data_kp = models.CharField(max_length=10)
    kp_pin_kp = models.CharField(max_length=4)
    kp_ile_sg = models.CharField(max_length=10)
    kp_nazw_sg = models.CharField(max_length=30)
    kp_data_sg = models.CharField(max_length=10)
    kp_pin_sg = models.CharField(max_length=4)
    kp_ile_p = models.CharField(max_length=10)
    kp_nazw_p = models.CharField(max_length=30)
    kp_data_p = models.CharField(max_length=10)
    kp_pin_p = models.CharField(max_length=4)
    gr_id = models.CharField(max_length=11)
    p_nr_fab = models.CharField(max_length=20)
    p_ind_rek = models.CharField(max_length=17)
    indeks = models.CharField(max_length=11)

class Karta_pr_st(models.Model):
    kp_nr = models.CharField(max_length=16)
    l_pesel = models.CharField(max_length=11)
    l_nazw_im = models.CharField(max_length=45)
    kp_data_wy = models.CharField(max_length=10)
    kp_stan = models.CharField(max_length=1)
    kp_norma_p = models.CharField(max_length=8)
    kp_rbh_n = models.CharField(max_length=10)
    kp_rbh_p = models.CharField(max_length=10)
    kp_bilans = models.CharField(max_length=8)
    kp_rbhm = models.CharField(max_length=10)
    kp_b_fund = models.CharField(max_length=10)
    kp_b_suma = models.CharField(max_length=10)
    kp_data_b = models.CharField(max_length=10)
    kp_nazw_kp = models.CharField(max_length=30)
    kp_data_kp = models.CharField(max_length=10)
    kp_pin_kp = models.CharField(max_length=4)
    kp_nazw_kj = models.CharField(max_length=30)
    kp_data_kj = models.CharField(max_length=10)
    kp_pin_kj = models.CharField(max_length=4)
    kp_nazw_kz = models.CharField(max_length=30)
    kp_data_kz = models.CharField(max_length=10)
    kp_pin_kz = models.CharField(max_length=4)
    kp_export = models.CharField(max_length=1)

class Karta_pr_st_arch(models.Model):
    kp_nr = models.CharField(max_length=16)
    l_pesel = models.CharField(max_length=11)
    l_nazw_im = models.CharField(max_length=45)
    kp_data_wy = models.CharField(max_length=10)
    kp_stan = models.CharField(max_length=1)
    kp_norma_p = models.CharField(max_length=8)
    kp_rbh_n = models.CharField(max_length=10)
    kp_rbh_p = models.CharField(max_length=10)
    kp_bilans = models.CharField(max_length=8)
    kp_rbhm = models.CharField(max_length=10)
    kp_b_fund = models.CharField(max_length=10)
    kp_b_suma = models.CharField(max_length=10)
    kp_data_b = models.CharField(max_length=10)
    kp_nazw_kp = models.CharField(max_length=30)
    kp_data_kp = models.CharField(max_length=10)
    kp_pin_kp = models.CharField(max_length=4)
    kp_nazw_kj = models.CharField(max_length=30)
    kp_data_kj = models.CharField(max_length=10)
    kp_pin_kj = models.CharField(max_length=4)
    kp_nazw_kz = models.CharField(max_length=30)
    kp_data_kz = models.CharField(max_length=10)
    kp_pin_kz = models.CharField(max_length=4)
    kp_export = models.CharField(max_length=1)

class Klasyf(models.Model):
    kwo_idx = models.CharField(max_length=20)
    kwo_nam = models.CharField(max_length=140)

class Ksiazka_k(models.Model):
    k_pr_sp_nr = models.CharField(max_length=15)
    bk_id = models.CharField(max_length=15)
    kp_nr = models.CharField(max_length=16)
    pr_id = models.CharField(max_length=10)
    p_nr_fab = models.CharField(max_length=20)
    p_typ = models.CharField(max_length=50)
    u_nazwa_s = models.CharField(max_length=12)
    k_do_k_n = models.CharField(max_length=1)
    k_do_data = models.CharField(max_length=19)
    k_do_pesel = models.CharField(max_length=11)
    k_do_nazw = models.CharField(max_length=40)
    k_do_datap = models.CharField(max_length=19)
    k_do_dec = models.CharField(max_length=40)
    k_do_ddata = models.CharField(max_length=19)
    k_sk_do = models.CharField(max_length=1)
    k_bk_pesel = models.CharField(max_length=11)
    k_bk_data = models.CharField(max_length=19)
    k_bk_dec = models.CharField(max_length=40)
    k_bk_ddata = models.CharField(max_length=19)
    kp_rbh_p = models.CharField(max_length=10)
    kp_rbh_n = models.CharField(max_length=10)
    k_data_sp = models.CharField(max_length=10)
    k_data_wa = models.CharField(max_length=10)
    k_pin_sp = models.CharField(max_length=4)
    k_nazw_kp = models.CharField(max_length=40)
    k_data_kp = models.CharField(max_length=10)
    k_pin_kp = models.CharField(max_length=4)
    k_stan_tk = models.CharField(max_length=1)
    k_temp = models.CharField(max_length=6)
    k_wilgoc = models.CharField(max_length=7)
    k_cisn = models.CharField(max_length=10)
    k_nap_zas = models.CharField(max_length=7)
    k_czes_zas = models.CharField(max_length=6)
    k_pr_stron = models.CharField(max_length=2)
    kp_prace = models.CharField(max_length=255)
    ostatni = models.CharField(max_length=19)
    k_pr_sp_po = models.CharField(max_length=60)
    k_pr_sp_wg = models.CharField(max_length=40)
    k_nazw_kj = models.CharField(max_length=40)
    k_data_kj = models.CharField(max_length=10)
    k_pin_kj = models.CharField(max_length=4)
    k_nazw_kz = models.CharField(max_length=40)
    k_data_kz = models.CharField(max_length=10)
    k_pin_kz = models.CharField(max_length=4)
    k_pr_sp_op = models.CharField(max_length=60)
    k_pr_sp_np = models.CharField(max_length=1)
    k_pilne = models.CharField(max_length=1)
    k_uwagi = models.CharField(max_length=100)
    k_zaznacz = models.CharField(max_length=1)
    p_excel = models.CharField(max_length=255)
    p_ind_rek = models.CharField(max_length=17)
    u_data_p = models.CharField(max_length=10)
    k_temp_k = models.CharField(max_length=6)
    k_wilgoc_k = models.CharField(max_length=7)
    k_cisn_k = models.CharField(max_length=10)
    rbh_b = models.CharField(max_length=5)
    kp_ps = models.CharField(max_length=255)
    k_data_spp = models.CharField(max_length=10)
    k_data_spk = models.CharField(max_length=10)
    nr_sw = models.CharField(max_length=21)
    nadzor = models.CharField(max_length=45)
    prot_spr = models.CharField(max_length=1)
    prot_kal = models.CharField(max_length=1)
    prot_ogr = models.CharField(max_length=1)
    wzor_od = models.CharField(max_length=1)
    wzor_rob = models.CharField(max_length=1)
    wzor_od_ro = models.CharField(max_length=1)
    indeks = models.CharField(max_length=11)

class Ksiazka_k_arch(models.Model):
    k_pr_sp_nr = models.CharField(max_length=15)
    bk_id = models.CharField(max_length=15)
    kp_nr = models.CharField(max_length=16)
    pr_id = models.CharField(max_length=10)
    p_nr_fab = models.CharField(max_length=20)
    p_typ = models.CharField(max_length=50)
    u_nazwa_s = models.CharField(max_length=12)
    k_do_k_n = models.CharField(max_length=1)
    k_do_data = models.CharField(max_length=19)
    k_do_pesel = models.CharField(max_length=11)
    k_do_nazw = models.CharField(max_length=40)
    k_do_datap = models.CharField(max_length=19)
    k_do_dec = models.CharField(max_length=40)
    k_do_ddata = models.CharField(max_length=19)
    k_sk_do = models.CharField(max_length=1)
    k_bk_pesel = models.CharField(max_length=11)
    k_bk_data = models.CharField(max_length=19)
    k_bk_dec = models.CharField(max_length=40)
    k_bk_ddata = models.CharField(max_length=19)
    kp_rbh_p = models.CharField(max_length=10)
    kp_rbh_n = models.CharField(max_length=10)
    k_data_sp = models.CharField(max_length=10)
    k_data_wa = models.CharField(max_length=10)
    k_pin_sp = models.CharField(max_length=4)
    k_nazw_kp = models.CharField(max_length=40)
    k_data_kp = models.CharField(max_length=10)
    k_pin_kp = models.CharField(max_length=4)
    k_stan_tk = models.CharField(max_length=1)
    k_temp = models.CharField(max_length=6)
    k_wilgoc = models.CharField(max_length=7)
    k_cisn = models.CharField(max_length=10)
    k_nap_zas = models.CharField(max_length=7)
    k_czes_zas = models.CharField(max_length=6)
    k_pr_stron = models.CharField(max_length=2)
    kp_prace = models.CharField(max_length=255)
    ostatni = models.CharField(max_length=19)
    k_pr_sp_po = models.CharField(max_length=60)
    k_pr_sp_wg = models.CharField(max_length=40)
    k_nazw_kj = models.CharField(max_length=40)
    k_data_kj = models.CharField(max_length=10)
    k_pin_kj = models.CharField(max_length=4)
    k_nazw_kz = models.CharField(max_length=40)
    k_data_kz = models.CharField(max_length=10)
    k_pin_kz = models.CharField(max_length=4)
    k_pr_sp_op = models.CharField(max_length=60)
    k_pr_sp_np = models.CharField(max_length=1)
    k_pilne = models.CharField(max_length=1)
    k_uwagi = models.CharField(max_length=100)
    k_zaznacz = models.CharField(max_length=1)
    p_excel = models.CharField(max_length=255)
    p_ind_rek = models.CharField(max_length=17)
    u_data_p = models.CharField(max_length=10)
    k_temp_k = models.CharField(max_length=6)
    k_wilgoc_k = models.CharField(max_length=7)
    k_cisn_k = models.CharField(max_length=10)
    rbh_b = models.CharField(max_length=5)
    kp_ps = models.CharField(max_length=255)
    k_data_spp = models.CharField(max_length=10)
    k_data_spk = models.CharField(max_length=10)
    nr_sw = models.CharField(max_length=21)
    nadzor = models.CharField(max_length=45)
    prot_spr = models.CharField(max_length=1)
    prot_kal = models.CharField(max_length=1)
    prot_ogr = models.CharField(max_length=1)
    wzor_od = models.CharField(max_length=1)
    wzor_rob = models.CharField(max_length=1)
    wzor_od_ro = models.CharField(max_length=1)
    indeks = models.CharField(max_length=11)

class Ksiazka_k_d(models.Model):
    k_pr_sp_nr = models.CharField(max_length=15)
    gr_id = models.CharField(max_length=2)
    nr_dr = models.CharField(max_length=5)
    data_dr = models.CharField(max_length=10)
    pr_id = models.CharField(max_length=10)
    powod = models.CharField(max_length=250)
    indeks = models.CharField(max_length=11)

class Ksiazka_k_d_arch(models.Model):
    k_pr_sp_nr = models.CharField(max_length=15)
    gr_id = models.CharField(max_length=2)
    nr_dr = models.CharField(max_length=5)
    data_dr = models.CharField(max_length=10)
    pr_id = models.CharField(max_length=10)
    powod = models.CharField(max_length=250)
    indeks = models.CharField(max_length=11)

class Meteo(models.Model):
    data = models.CharField(max_length=10)
    czas = models.CharField(max_length=5)
    p1 = models.CharField(max_length=7)
    p2 = models.CharField(max_length=5)
    p3 = models.CharField(max_length=5)
    p4 = models.CharField(max_length=5)
    p5 = models.CharField(max_length=5)
    p6 = models.CharField(max_length=5)
    p7 = models.CharField(max_length=5)
    p8 = models.CharField(max_length=5)
    p9 = models.CharField(max_length=5)
    p10 = models.CharField(max_length=5)
    p11 = models.CharField(max_length=5)
    p12 = models.CharField(max_length=5)
    p13 = models.CharField(max_length=5)
    p14 = models.CharField(max_length=5)
    p15 = models.CharField(max_length=5)
    p16 = models.CharField(max_length=5)
    p17 = models.CharField(max_length=5)
    p18 = models.CharField(max_length=5)
    p19 = models.CharField(max_length=5)
    p20 = models.CharField(max_length=5)
    p21 = models.CharField(max_length=5)
    p22 = models.CharField(max_length=5)
    p23 = models.CharField(max_length=5)
    p24 = models.CharField(max_length=5)
    p25 = models.CharField(max_length=5)
    p26 = models.CharField(max_length=5)
    p27 = models.CharField(max_length=5)
    p28 = models.CharField(max_length=5)
    p29 = models.CharField(max_length=5)
    p30 = models.CharField(max_length=5)
    p31 = models.CharField(max_length=5)
    p32 = models.CharField(max_length=5)
    p33 = models.CharField(max_length=5)

class Odbior_up(models.Model):
    id_odb = models.CharField(max_length=11)
    o_nazwisko = models.CharField(max_length=30)
    o_imie = models.CharField(max_length=15)
    o_nr_up = models.CharField(max_length=20)
    o_zkad = models.CharField(max_length=6)

class Om_zu(models.Model):
    indeks = models.CharField(max_length=11)
    zwo = models.CharField(max_length=1)
    zdich = models.CharField(max_length=1)
    zkepp = models.CharField(max_length=1)
    zkppwf = models.CharField(max_length=1)
    zkpd = models.CharField(max_length=1)
    om = models.CharField(max_length=1)

class Osta_imp(models.Model):
    o_u_id = models.CharField(max_length=7)
    data_imp = models.CharField(max_length=19)
    data_eksp = models.CharField(max_length=19)

class Pdf_dirs(models.Model):
    usernam = models.CharField(max_length=20)
    dir_zak = models.CharField(max_length=50)

class Pdf_protspr(models.Model):
    ind_rek = models.CharField(max_length=17)
    gr_id = models.CharField(max_length=20)
    p_typ = models.CharField(max_length=50)
    p_nr_fab = models.CharField(max_length=20)
    pdf_name = models.CharField(max_length=120)
    pdf_date = models.CharField(max_length=19)
    k_pr_sp_nr = models.CharField(max_length=15)
    pdf_dir = models.CharField(max_length=50)
    indeks = models.CharField(max_length=11)



class Pers_kar(models.Model):
    l_pesel = models.CharField(max_length=11)
    k_od = models.CharField(max_length=10)
    k_do = models.CharField(max_length=10)
    k_opis = models.CharField(max_length=40)
    k_miasto = models.CharField(max_length=15)
    k_wc = models.CharField(max_length=2)
    k_staz = models.CharField(max_length=2)

class Pers_nob(models.Model):
    l_pesel = models.CharField(max_length=11)
    l_ob_id = models.CharField(max_length=3)
    l_nob_do = models.CharField(max_length=10)
    l_nob_od = models.CharField(max_length=10)
    l_godz = models.CharField(max_length=4)
    l_tf = models.CharField(max_length=1)
    l_nob_st = models.CharField(max_length=2)
    l_rozkaz = models.CharField(max_length=40)
    opis = models.CharField(max_length=255)
    l_pt = models.CharField(max_length=1)

class Pers_nob_arch(models.Model):
    l_pesel = models.CharField(max_length=11)
    l_ob_id = models.CharField(max_length=3)
    l_nob_do = models.CharField(max_length=10)
    l_nob_od = models.CharField(max_length=10)
    l_godz = models.CharField(max_length=4)
    l_tf = models.CharField(max_length=1)
    l_nob_st = models.CharField(max_length=2)
    l_rozkaz = models.CharField(max_length=40)
    opis = models.CharField(max_length=255)
    l_pt = models.CharField(max_length=1)


class Pgrupa1_me(models.Model):
    gr_id = models.CharField(max_length=8)
    gr_nazwa = models.CharField(max_length=70)
    ind_rek = models.CharField(max_length=17)

class Pgrupa2_me(models.Model):
    gr_id = models.CharField(max_length=8)
    gr_nazwa = models.CharField(max_length=70)
    ind_rek = models.CharField(max_length=17)

class Pgrupa3_me(models.Model):
    gr_id = models.CharField(max_length=8)
    gr_nazwa = models.CharField(max_length=70)
    ind_rek = models.CharField(max_length=17)

class Plan_daty(models.Model):
    om_id = models.CharField(max_length=7)
    styczen = models.CharField(max_length=10)
    luty = models.CharField(max_length=10)
    marzec = models.CharField(max_length=10)
    kwiecien = models.CharField(max_length=10)
    maj = models.CharField(max_length=10)
    czerwiec = models.CharField(max_length=10)
    lipiec = models.CharField(max_length=10)
    sierpien = models.CharField(max_length=10)
    wrzesien = models.CharField(max_length=10)
    pazdzier = models.CharField(max_length=10)
    listopad = models.CharField(max_length=10)
    grudzien = models.CharField(max_length=10)

class Plan_rok(models.Model):
    ind_rek = models.CharField(max_length=17)
    u_data_pl = models.CharField(max_length=10)
    k_data_pl = models.CharField(max_length=10)
    k_data_pl1 = models.CharField(max_length=10)
    k_data_pl2 = models.CharField(max_length=10)
    k_data_pl3 = models.CharField(max_length=10)
    k_data_pl4 = models.CharField(max_length=10)
    pr_id = models.CharField(max_length=10)
    a_data_pl = models.CharField(max_length=10)

class Plan_rok_om(models.Model):
    ind_rek = models.CharField(max_length=17)
    k_data_pl = models.CharField(max_length=10)
    k_data_pl1 = models.CharField(max_length=10)
    k_data_pl2 = models.CharField(max_length=10)
    k_data_pl3 = models.CharField(max_length=10)
    k_data_pl4 = models.CharField(max_length=10)
    pr_id = models.CharField(max_length=10)
    id_stat_pl = models.CharField(max_length=4)
    u_nazwa_s = models.CharField(max_length=12)
    p_norma = models.CharField(max_length=6)
    a_data_pl = models.CharField(max_length=10)
    bok_id = models.CharField(max_length=15)

class Plan_rok_om_arch(models.Model):
    ind_rek = models.CharField(max_length=17)
    k_data_pl = models.CharField(max_length=10)
    k_data_pl1 = models.CharField(max_length=10)
    k_data_pl2 = models.CharField(max_length=10)
    k_data_pl3 = models.CharField(max_length=10)
    k_data_pl4 = models.CharField(max_length=10)
    pr_id = models.CharField(max_length=10)
    id_stat_pl = models.CharField(max_length=4)
    u_nazwa_s = models.CharField(max_length=12)
    p_norma = models.CharField(max_length=6)
    a_data_pl = models.CharField(max_length=10)
    bok_id = models.CharField(max_length=15)

class Plan_swieta(models.Model):
    swieto = models.CharField(max_length=12)
    data_s = models.CharField(max_length=10)
    data_z = models.CharField(max_length=10)

class Plan_udod(models.Model):
    du_data_pl = models.CharField(max_length=10)
    ind_rek = models.CharField(max_length=17)

class Pomoc(models.Model):
    lp = models.CharField(max_length=3)
    temat = models.CharField(max_length=50)
    notes = models.CharField(max_length=255)

class Przyrzad_ar(models.Model):
    gr_id = models.CharField(max_length=11)
    p_nr_fab = models.CharField(max_length=20)
    p_rok_prod = models.CharField(max_length=4)
    bk_id = models.CharField(max_length=15)
    om_id = models.CharField(max_length=7)
    pr_id = models.CharField(max_length=10)
    u_data_pl = models.CharField(max_length=10)
    k_data_pl = models.CharField(max_length=10)
    k_data_sp = models.CharField(max_length=10)
    k_data_wa = models.CharField(max_length=10)
    k_nr_ewid = models.CharField(max_length=15)
    k_pr_st = models.CharField(max_length=255)
    k_pr_st_nr = models.CharField(max_length=15)
    k_pr_sp_np = models.CharField(max_length=1)
    k_stan_tk = models.CharField(max_length=1)
    l_pesel = models.CharField(max_length=11)
    p_kat = models.CharField(max_length=2)
    p_proc = models.CharField(max_length=6)
    p_prop_rok = models.CharField(max_length=4)
    p_prop_zg = models.CharField(max_length=30)
    p_wybrak = models.CharField(max_length=1)
    p_uz_kon = models.CharField(max_length=1)
    p_zm_id = models.CharField(max_length=9)
    u_data_td = models.CharField(max_length=10)
    u_data_to = models.CharField(max_length=10)
    u_id = models.CharField(max_length=7)
    p_form = models.CharField(max_length=255)
    p_prac_sum = models.CharField(max_length=10)
    p_prac_nap = models.CharField(max_length=10)
    mp_id = models.CharField(max_length=3)
    p_data_wyb = models.CharField(max_length=10)
    p_prot_wyb = models.CharField(max_length=15)
    slu_id = models.CharField(max_length=2)
    pod_id = models.CharField(max_length=2)
    spr_id = models.CharField(max_length=3)
    odp_id = models.CharField(max_length=3)
    uwagi = models.CharField(max_length=255)
    p_eksport = models.CharField(max_length=10)
    nsn = models.CharField(max_length=13)
    ind_rek = models.CharField(max_length=17)
    kod_ean8 = models.CharField(max_length=8)
    indeks = models.CharField(max_length=11)
    gwar_data = models.CharField(max_length=10)
    wpd = models.CharField(max_length=2)
    p_kal_nt = models.CharField(max_length=1)
    jim_spw = models.CharField(max_length=13)
    nr_zwsir = models.CharField(max_length=25)
    nazwa_spw = models.CharField(max_length=50)

class Przyrzad_bk(models.Model):
    gr_id = models.CharField(max_length=11)
    p_nr_fab = models.CharField(max_length=15)
    p_rok_prod = models.CharField(max_length=4)
    bk_id = models.CharField(max_length=15)
    om_id = models.CharField(max_length=7)
    pr_id = models.CharField(max_length=10)
    u_data_pl = models.CharField(max_length=10)
    k_data_pl = models.CharField(max_length=10)
    k_data_sp = models.CharField(max_length=10)
    k_data_wa = models.CharField(max_length=10)
    k_nr_ewid = models.CharField(max_length=15)
    k_pr_st = models.CharField(max_length=255)
    k_pr_st_nr = models.CharField(max_length=15)
    k_pr_sp_np = models.CharField(max_length=1)
    k_stan_tk = models.CharField(max_length=1)
    l_pesel = models.CharField(max_length=11)
    p_kat = models.CharField(max_length=2)
    p_proc = models.CharField(max_length=6)
    p_prop_rok = models.CharField(max_length=4)
    p_prop_zg = models.CharField(max_length=30)
    p_wybrak = models.CharField(max_length=1)
    p_uz_kon = models.CharField(max_length=1)
    p_zm_id = models.CharField(max_length=9)
    u_data_td = models.CharField(max_length=10)
    u_data_to = models.CharField(max_length=10)
    u_id = models.CharField(max_length=7)
    p_form = models.CharField(max_length=255)
    p_prac_sum = models.CharField(max_length=10)
    p_prac_nap = models.CharField(max_length=10)
    mp_id = models.CharField(max_length=3)
    p_data_wyb = models.CharField(max_length=10)
    p_prot_wyb = models.CharField(max_length=15)
    slu_id = models.CharField(max_length=2)
    pod_id = models.CharField(max_length=2)
    spr_id = models.CharField(max_length=3)
    odp_id = models.CharField(max_length=3)
    uwagi = models.CharField(max_length=255)
    p_eksport = models.CharField(max_length=10)
    nsn = models.CharField(max_length=13)
    ind_rek = models.CharField(max_length=17)
    p_import = models.CharField(max_length=1)
    p_bok = models.CharField(max_length=1)

class Przyrzad_pr(models.Model):
    p_nr_fab = models.CharField(max_length=20)
    om_id = models.CharField(max_length=7)
    k_pr_st_nr = models.CharField(max_length=15)
    pr_data = models.CharField(max_length=10)
    pr_podlega = models.CharField(max_length=50)
    pr_opis_st = models.CharField(max_length=255)
    pr_braki = models.CharField(max_length=255)
    pr_wnioski = models.CharField(max_length=255)
    pr_podst = models.CharField(max_length=50)
    pr_komis_1 = models.CharField(max_length=40)
    pr_komis_p = models.CharField(max_length=4)
    pr_komis_2 = models.CharField(max_length=40)
    pr_komis_3 = models.CharField(max_length=40)
    pr_op_txt = models.CharField(max_length=255)
    pr_op_pin = models.CharField(max_length=4)
    pr_op_nazw = models.CharField(max_length=40)
    pr_op_data = models.CharField(max_length=10)
    pr_de_txt = models.CharField(max_length=255)
    pr_de_data = models.CharField(max_length=10)
    p_ind_rek = models.CharField(max_length=17)
    indeks = models.CharField(max_length=11)
    k_pr_sp_nr = models.CharField(max_length=15)
    kod_ean8 = models.CharField(max_length=8)
    u_id = models.CharField(max_length=7)

class Przyrzad_st(models.Model):
    gr_id = models.CharField(max_length=11)
    nsn = models.CharField(max_length=13)
    p_nazwa = models.CharField(max_length=40)
    p_typ = models.CharField(max_length=50)
    om_id = models.CharField(max_length=7)
    p_indeks = models.CharField(max_length=10)
    p_prod = models.CharField(max_length=10)
    p_jm = models.CharField(max_length=10)
    p_pwaz_k = models.CharField(max_length=5)
    p_pwaz_u = models.CharField(max_length=5)
    p_norma_k = models.CharField(max_length=6)
    p_norma_u = models.CharField(max_length=6)
    p_norma_w = models.CharField(max_length=6)
    p_komplet = models.CharField(max_length=255)
    p_tech = models.CharField(max_length=255)
    p_metoda = models.CharField(max_length=255)
    p_metodyka = models.CharField(max_length=255)
    p_wymgania = models.CharField(max_length=255)
    p_excel = models.CharField(max_length=255)
    ind_rek = models.CharField(max_length=17)
    kwo_idx = models.CharField(max_length=20)
    jim_idx = models.CharField(max_length=13)
    jim_opis = models.CharField(max_length=255)

class Przyrzad_zm(models.Model):
    p_nr_fab = models.CharField(max_length=20)
    p_rok_prod = models.CharField(max_length=4)
    bk_id = models.CharField(max_length=15)
    om_id = models.CharField(max_length=7)
    pr_id = models.CharField(max_length=10)
    u_data_pl = models.CharField(max_length=10)
    k_data_sp = models.CharField(max_length=10)
    k_data_wa = models.CharField(max_length=10)
    k_nr_ewid = models.CharField(max_length=15)
    k_pr_st = models.CharField(max_length=255)
    k_pr_st_nr = models.CharField(max_length=15)
    k_pr_sp_np = models.CharField(max_length=1)
    k_stan_tk = models.CharField(max_length=1)
    l_pesel = models.CharField(max_length=11)
    p_kat = models.CharField(max_length=2)
    p_proc = models.CharField(max_length=6)
    p_prop_rok = models.CharField(max_length=4)
    p_prop_zg = models.CharField(max_length=30)
    p_wybrak = models.CharField(max_length=1)
    p_uz_kon = models.CharField(max_length=1)
    p_zm_id = models.CharField(max_length=9)
    u_data_td = models.CharField(max_length=10)
    u_data_to = models.CharField(max_length=10)
    u_id = models.CharField(max_length=7)
    p_form = models.CharField(max_length=255)
    p_prac_sum = models.CharField(max_length=10)
    p_prac_nap = models.CharField(max_length=10)
    mp_id = models.CharField(max_length=3)
    p_data_wyb = models.CharField(max_length=10)
    p_prot_wyb = models.CharField(max_length=15)
    slu_id = models.CharField(max_length=2)
    pod_id = models.CharField(max_length=2)
    spr_id = models.CharField(max_length=3)
    odp_id = models.CharField(max_length=3)
    uwagi = models.CharField(max_length=255)
    p_eksport = models.CharField(max_length=10)
    nsn = models.CharField(max_length=13)
    ind_rek = models.CharField(max_length=17)
    p_import = models.CharField(max_length=1)
    p_bok = models.CharField(max_length=1)
    p_om_id = models.CharField(max_length=7)
    prot_p = models.CharField(max_length=20)
    data_om = models.CharField(max_length=10)
    p_tab = models.CharField(max_length=1)
    p_etat = models.CharField(max_length=1)
    kod_ean8 = models.CharField(max_length=8)
    c_f_kont = models.CharField(max_length=1)
    l_t_uzyt = models.CharField(max_length=1)
    c_jaki_prz = models.CharField(max_length=1)
    l_przydat = models.CharField(max_length=1)
    n_cz_kal = models.CharField(max_length=2)
    indeks = models.CharField(max_length=11)
    jim_idx = models.CharField(max_length=13)
    gwar_data = models.CharField(max_length=10)
    wpd = models.CharField(max_length=2)
    cbd_akc = models.CharField(max_length=1)
    p_kal_nt = models.CharField(max_length=1)
    jim_spw = models.CharField(max_length=13)
    nr_zwsir = models.CharField(max_length=25)
    nazwa_spw = models.CharField(max_length=50)

class Przyrzad_zmcbd(models.Model):
    indeks = models.CharField(max_length=11)
    p_nr_fab = models.CharField(max_length=20)
    u_id = models.CharField(max_length=7)
    om_id = models.CharField(max_length=7)
    pr_id = models.CharField(max_length=10)
    u_data_pl = models.CharField(max_length=10)
    k_data_wa = models.CharField(max_length=10)
    k_stan_tk = models.CharField(max_length=1)
    p_zm_id = models.CharField(max_length=9)
    kod_ean8 = models.CharField(max_length=8)
    ind_rek = models.CharField(max_length=17)
    akcept = models.CharField(max_length=1)
    p_kal_nt = models.CharField(max_length=1)

class Przyrzad_zm_kk(models.Model):
    gr_id = models.CharField(max_length=11)
    p_nr_fab = models.CharField(max_length=20)
    p_rok_prod = models.CharField(max_length=4)
    bk_id = models.CharField(max_length=15)
    om_id = models.CharField(max_length=7)
    pr_id = models.CharField(max_length=10)
    u_data_pl = models.CharField(max_length=10)
    k_data_sp = models.CharField(max_length=10)
    k_data_wa = models.CharField(max_length=10)
    k_nr_ewid = models.CharField(max_length=15)
    k_pr_st = models.CharField(max_length=255)
    k_pr_st_nr = models.CharField(max_length=15)
    k_pr_sp_np = models.CharField(max_length=1)
    k_stan_tk = models.CharField(max_length=1)
    l_pesel = models.CharField(max_length=11)
    p_kat = models.CharField(max_length=2)
    p_proc = models.CharField(max_length=6)
    p_prop_rok = models.CharField(max_length=4)
    p_prop_zg = models.CharField(max_length=30)
    p_wybrak = models.CharField(max_length=1)
    p_uz_kon = models.CharField(max_length=1)
    p_zm_id = models.CharField(max_length=9)
    u_data_td = models.CharField(max_length=10)
    u_data_to = models.CharField(max_length=10)
    u_id = models.CharField(max_length=7)
    p_form = models.CharField(max_length=255)
    p_prac_sum = models.CharField(max_length=10)
    p_prac_nap = models.CharField(max_length=10)
    mp_id = models.CharField(max_length=3)
    p_data_wyb = models.CharField(max_length=10)
    p_prot_wyb = models.CharField(max_length=15)
    slu_id = models.CharField(max_length=2)
    pod_id = models.CharField(max_length=2)
    spr_id = models.CharField(max_length=3)
    odp_id = models.CharField(max_length=3)
    uwagi = models.CharField(max_length=255)
    p_eksport = models.CharField(max_length=10)
    nsn = models.CharField(max_length=13)
    ind_rek = models.CharField(max_length=17)
    p_import = models.CharField(max_length=1)
    p_bok = models.CharField(max_length=1)
    p_om_id = models.CharField(max_length=7)
    prot_p = models.CharField(max_length=20)
    data_om = models.CharField(max_length=10)
    p_tab = models.CharField(max_length=1)
    p_etat = models.CharField(max_length=1)
    kod_ean8 = models.CharField(max_length=8)
    c_f_kont = models.CharField(max_length=1)
    l_t_uzyt = models.CharField(max_length=1)
    c_jaki_prz = models.CharField(max_length=1)
    l_przydat = models.CharField(max_length=1)
    n_cz_kal = models.CharField(max_length=2)
    indeks = models.CharField(max_length=11)
    jim_idx = models.CharField(max_length=13)
    gwar_data = models.CharField(max_length=10)
    wpd = models.CharField(max_length=2)

class Rejon(models.Model):
    ind_rek = models.CharField(max_length=9)
    u_id = models.CharField(max_length=7)
    u_nazwa_s = models.CharField(max_length=15)
    u_miasto = models.CharField(max_length=20)

class Stanow_met(models.Model):
    st_id = models.CharField(max_length=19)
    pr_id = models.CharField(max_length=10)
    st_e_k = models.CharField(max_length=1)
    l_pesel = models.CharField(max_length=11)
    st_kod = models.CharField(max_length=4)
    st_nazwa = models.CharField(max_length=60)
    st_rodz = models.CharField(max_length=2)
    st_stop_et = models.CharField(max_length=2)
    st_grupa = models.CharField(max_length=2)
    st_kat = models.CharField(max_length=2)

class Stos_plan(models.Model):
    sp_ind_rek = models.CharField(max_length=17)
    sp_p_gen = models.CharField(max_length=3)
    sp_d_gen = models.CharField(max_length=19)
    sp_kto_gen = models.CharField(max_length=30)
    p_ind_rek = models.CharField(max_length=17)
    k_data_pl = models.CharField(max_length=10)
    pr_id = models.CharField(max_length=10)
    id_stat_pl = models.CharField(max_length=4)
    u_nazwa_s = models.CharField(max_length=12)
    u_id = models.CharField(max_length=7)
    sp_t_pola = models.CharField(max_length=1)
    sp_pole = models.CharField(max_length=10)
    sp_akcja = models.CharField(max_length=1)
    sp_war_n = models.CharField(max_length=20)
    sp_war_s = models.CharField(max_length=20)
    sp_og_d_iz = models.CharField(max_length=10)
    sp_og_k_iz = models.CharField(max_length=30)
    sp_as_d_z = models.CharField(max_length=10)
    sp_as_k_z = models.CharField(max_length=30)
    sp_as_id = models.CharField(max_length=7)
    sp_cbd_d_z = models.CharField(max_length=10)
    sp_cbd_k_z = models.CharField(max_length=30)
    sp_id_as_a = models.CharField(max_length=7)
    sp_d_as_wi = models.CharField(max_length=10)
    sp_d_cbd_w = models.CharField(max_length=10)

class Swiadectwa(models.Model):
    sw_nr = models.CharField(max_length=4)
    sw_nr_pr = models.CharField(max_length=12)
    sw_nr_data = models.CharField(max_length=10)
    k_pr_sp_nr = models.CharField(max_length=15)
    sw_stron = models.CharField(max_length=4)
    sw_wyn_p = models.CharField(max_length=4)
    sw_wyn_k = models.CharField(max_length=4)
    sw_poza = models.CharField(max_length=1)
    sw_praw_r = models.CharField(max_length=4)
    sw_wspol_k = models.CharField(max_length=8)
    sw_ponow = models.CharField(max_length=1)
    sw_ponow_p = models.CharField(max_length=22)
    sw_str_ogr = models.CharField(max_length=4)
    sw_gdzie_w = models.CharField(max_length=4)

class Temp(models.Model):
    indeks = models.CharField(max_length=11)
    zwo = models.CharField(max_length=1)
    zdich = models.CharField(max_length=1)
    zkepp = models.CharField(max_length=1)
    zkppwf = models.CharField(max_length=1)
    zkpd = models.CharField(max_length=1)
    om = models.CharField(max_length=1)

class Temp1(models.Model):
    indeks = models.CharField(max_length=11)
    zwo = models.CharField(max_length=1)
    zdich = models.CharField(max_length=1)
    zkepp = models.CharField(max_length=1)
    zkppwf = models.CharField(max_length=1)
    zkpd = models.CharField(max_length=1)
    om = models.CharField(max_length=1)

class Terminy(models.Model):
    dzien = models.CharField(max_length=10)
    rodzaj = models.CharField(max_length=1)
    roboczy = models.CharField(max_length=1)
    godzin_m = models.CharField(max_length=10)

class Upr_lm(models.Model):
    nr_lm = models.CharField(max_length=4)
    up_om_id = models.CharField(max_length=7)
    up_dataw = models.CharField(max_length=10)
    up_wydnr = models.CharField(max_length=4)

class Upr_zak_lm(models.Model):
    pr_id = models.CharField(max_length=10)
    z_podgr = models.CharField(max_length=6)
    z_zakr = models.CharField(max_length=30)
    z_niep = models.CharField(max_length=15)
    z_proc = models.CharField(max_length=60)
    z_uwagi = models.CharField(max_length=20)

class Uzg_ddpplan(models.Model):
    p_ind_rek = models.CharField(max_length=17)
    ses_id = models.CharField(max_length=17)
    uzg_ddpp = models.CharField(max_length=10)
    imp_date = models.CharField(max_length=10)

class Wyjazd(models.Model):
    om_id = models.CharField(max_length=7)
    data_wyj = models.CharField(max_length=10)
    is_check = models.CharField(max_length=1)

class Finanse(models.Model):
    fi_zus = models.CharField(max_length=10)
    fi_koszty = models.CharField(max_length=10)
    fi_pod_01 = models.CharField(max_length=10)
    fi_pod_02 = models.CharField(max_length=10)
    fi_pod_03 = models.CharField(max_length=10)
    fi_czas_pr = models.CharField(max_length=5)
    fi_nor_pcw = models.CharField(max_length=4)
    fi_nor_zz = models.CharField(max_length=4)
    fi_data_kp = models.CharField(max_length=10)
    ddw = models.CharField(max_length=70)
    ddw_kat = models.CharField(max_length=1)
    podpis_fax = models.CharField(max_length=30)
    rbh_tab = models.CharField(max_length=10)
    szt_tab = models.CharField(max_length=10)
    sp_data = models.CharField(max_length=8)

class Grupa(models.Model):
    gr_id = models.CharField(max_length=2)
    opis = models.CharField(max_length=40)

class Klasa(models.Model):
    gr_id = models.CharField(max_length=4)
    opis = models.CharField(max_length=90)

class Konfig(models.Model):
    konf_opis = models.CharField(max_length=100)
    is_checked = models.CharField(max_length=1)
    om_id = models.CharField(max_length=7)

class Meteo_pr(models.Model):
    numer = models.CharField(max_length=2)
    nazwa = models.CharField(max_length=5)
    blad_t = models.CharField(max_length=5)
    blad_w = models.CharField(max_length=5)

class Mw_odp(models.Model):
    odp_id = models.CharField(max_length=3)
    u_id = models.CharField(max_length=7)
    nazwa = models.CharField(max_length=40)

class Mw_pod(models.Model):
    pod_id = models.CharField(max_length=2)
    u_id = models.CharField(max_length=7)
    nazwa = models.CharField(max_length=40)

class Mw_slu(models.Model):
    slu_id = models.CharField(max_length=2)
    nazwa = models.CharField(max_length=40)

class Mw_spr(models.Model):
    spr_id = models.CharField(max_length=3)
    u_id = models.CharField(max_length=7)
    nazwa = models.CharField(max_length=40)

class Nbc(models.Model):
    kod_nbc = models.CharField(max_length=2)
    kraj = models.CharField(max_length=20)

class Osrodek_met(models.Model):
    om_id = models.CharField(max_length=7)
    om_nazwa_p = models.CharField(max_length=50)
    om_nazwa_s = models.CharField(max_length=6)
    om_kod = models.CharField(max_length=6)
    om_miasto = models.CharField(max_length=30)
    om_ulica = models.CharField(max_length=40)
    om_fax = models.CharField(max_length=35)
    ind_rek = models.CharField(max_length=17)
    ind_poczta = models.CharField(max_length=1)
    om_is_wom = models.CharField(max_length=1)
    om_tel = models.CharField(max_length=11)
    om_email = models.CharField(max_length=16)
    om_www = models.CharField(max_length=35)

class Osrodek_pr(models.Model):
    pr_id = models.CharField(max_length=10)
    pr_nazwa_p = models.CharField(max_length=62)
    pr_nazwa_s = models.CharField(max_length=12)
    pr_kod = models.CharField(max_length=6)
    pr_miasto = models.CharField(max_length=30)
    pr_ulica = models.CharField(max_length=40)
    pr_fax = models.CharField(max_length=35)
    ind_rek = models.CharField(max_length=17)
    ind_poczta = models.CharField(max_length=1)

class Pers_ob(models.Model):
    l_ob_id = models.CharField(max_length=3)
    l_nazwa = models.CharField(max_length=40)
    l_tf = models.CharField(max_length=1)

class Plan_status(models.Model):
    id_stat_pl = models.CharField(max_length=4)
    st_stat_pl = models.CharField(max_length=12)

class Pyt_kn(models.Model):
    nazwa = models.CharField(max_length=20)
    kod = models.CharField(max_length=1)

class Pyt_podstawa(models.Model):
    kod = models.CharField(max_length=2)
    nazwa = models.CharField(max_length=30)

class Pyt_pw(models.Model):
    odp_nazwa = models.CharField(max_length=15)
    l_nob_st = models.CharField(max_length=2)

class Pyt_tn(models.Model):
    pyt_nazwa = models.CharField(max_length=16)
    pyt_id = models.CharField(max_length=2)

class Pyt_wc(models.Model):
    odp_nazwa = models.CharField(max_length=15)
    l_nob_st = models.CharField(max_length=2)

class Sl_rejon(models.Model):
    ind_rek = models.CharField(max_length=9)
    nazwa = models.CharField(max_length=40)

class Sl_sta(models.Model):
    kod = models.CharField(max_length=4)
    nazwa = models.CharField(max_length=60)
    kom_etat = models.CharField(max_length=1)

class Sl_stopien(models.Model):
    kod = models.CharField(max_length=2)
    nazwa = models.CharField(max_length=40)
    nazwa_sk = models.CharField(max_length=30)
    na_kol = models.CharField(max_length=3)

class Sl_sz_rp(models.Model):
    nazwa = models.CharField(max_length=40)
    sz_1 = models.CharField(max_length=2)
    sz_2 = models.CharField(max_length=2)
    sz_3 = models.CharField(max_length=2)
    sz_4 = models.CharField(max_length=2)

class Ugrupa_me(models.Model):
    gr_id = models.CharField(max_length=4)
    gr_u_nazwa = models.CharField(max_length=30)

class Uzytkownik(models.Model):
    sz_ind = models.CharField(max_length=8)
    u_id = models.CharField(max_length=7)
    u_nazwa_s = models.CharField(max_length=12)
    u_nazwa_p = models.CharField(max_length=48)
    u_kod_p = models.CharField(max_length=6)
    u_miasto = models.CharField(max_length=30)
    u_ulica = models.CharField(max_length=40)
    u_krypt = models.CharField(max_length=20)
    u_fax = models.CharField(max_length=20)
    u_metro = models.CharField(max_length=30)
    u_metro_te = models.CharField(max_length=20)
    u_szef = models.CharField(max_length=30)
    u_szef_t = models.CharField(max_length=20)
    u_techn = models.CharField(max_length=30)
    u_techn_t = models.CharField(max_length=20)
    ind_rek = models.CharField(max_length=17)
    om_id = models.CharField(max_length=7)
    u_adresat = models.CharField(max_length=48)
    u_metro_et = models.CharField(max_length=1)
    u_met_up_n = models.CharField(max_length=15)

class Uzyt_mp(models.Model):
    mp_id = models.CharField(max_length=3)
    mp_nazwa = models.CharField(max_length=20)

class Uzyt_og(models.Model):
    sz_ind = models.CharField(max_length=8)
    u_id = models.CharField(max_length=7)
    u_nazwa_s = models.CharField(max_length=12)
    u_nazwa_p = models.CharField(max_length=48)
    u_kod_p = models.CharField(max_length=6)
    u_miasto = models.CharField(max_length=30)
    u_ulica = models.CharField(max_length=40)
    u_krypt = models.CharField(max_length=20)
    u_fax = models.CharField(max_length=20)
    u_metro = models.CharField(max_length=30)
    u_metro_te = models.CharField(max_length=20)
    u_szef = models.CharField(max_length=30)
    u_szef_t = models.CharField(max_length=20)
    u_techn = models.CharField(max_length=30)
    u_techn_t = models.CharField(max_length=20)
    ind_rek = models.CharField(max_length=17)
    om_id = models.CharField(max_length=7)
    u_metro_et = models.CharField(max_length=1)
    u_met_up_n = models.CharField(max_length=15)
    u_adresat = models.CharField(max_length=48)


def reset_id_sequence(model_name: str):
    with connection.cursor() as cursor:
        cursor.execute(f"DELETE FROM sqlite_sequence WHERE name='{model_name}';")


def create_records_from_dataframe(df, model, foreign_keys=None):
    """
    Create database records from a given dataframe.

    :param df: DataFrame to be converted into database records
    :param model: Django Model class for the database table where records will be created
    :param foreign_keys: A dictionary with data frame column names as keys.
        The value for each key is a tuple, the first element is a Django Model
        representing the foreign table (foreign_model), the second element is a string
        representing the lookup field in the foreign table (foreign_key_lookup)
        foreign_key_df_field: Represents the field in the dataframe which needs to be replaced with the
        corresponding foreign key object.
        foreign_model: The Django Model which is referenced as a foreign key.
        foreign_key_lookup: The field in the foreign_model used for looking up the corresponding foreign key object.
    """
    for index, row in df.iterrows():
        data = row.to_dict()

        if foreign_keys:
            for foreign_key_df_field, (foreign_model, foreign_key_lookup) in foreign_keys.items():
                try:
                    foreign_obj = foreign_model.objects.get(**{foreign_key_lookup: data[foreign_key_df_field]})
                    # Replace the foreign key value in the data with the actual foreign object
                    data[model._meta.get_field(foreign_key_df_field).name] = foreign_obj
                    # Remove the original foreign key field from the data
                    del data[foreign_key_df_field]
                except foreign_model.DoesNotExist:
                    print(
                        f"No match for {foreign_key_lookup}: {data[foreign_key_df_field]} in table {model._meta.db_table}, skipping row.")
                    continue  # Skip the current row if the foreign key does not exist

        # Create a model object and save it to database
        model.objects.create(**data)


def print_all_records(model, verbose=False):
    for obj in model.objects.all():
        if verbose:
            print(obj.__dict__)


def df_to_django_model(df: pd.DataFrame, DjangoModel: Type[Model], foreign_keys=None, verbose=False) -> None:
    with transaction.atomic():
        DjangoModel.objects.all().delete()
        reset_id_sequence(DjangoModel._meta.db_table)
        create_records_from_dataframe(df, DjangoModel, foreign_keys)
    print_all_records(DjangoModel, verbose)


if __name__ == '__main__':
    dl = DataLoader()

    df_pers_st = dl.pers_st
    df_to_django_model(df_pers_st, Pers_st, verbose=False)

    df_pers_gr = dl.pers_gr
    print(f'df_pers_st: {df_pers_st.columns}')
    print(f'df_pers_gr: {df_pers_gr.columns}')

    foreign_keys_pers_gr = {'foreign_keys': (Pers_st, 'l_pesel')}
    df_to_django_model(df_pers_gr, Pers_gr, foreign_keys=foreign_keys_pers_gr, verbose=False)