from django.core.management import call_command
from django.db import models, connection
import pandas as pd


# Create your models here.
class Pers_st(models.Model):
    l_pesel = models.CharField(max_length=11,unique=True)
    l_nazwisko = models.CharField(max_length=30)
    l_imie = models.CharField(max_length=15)
    l_nazw_im = models.CharField(max_length=45)
    l_login = models.CharField(max_length=45)
    sp_id = models.CharField(max_length=3)
    sw_id = models.CharField(max_length=3)
    sw2_id = models.CharField(max_length=3)
    l_grupa = models.CharField(max_length=1)
    l_kl3 = models.CharField(max_length=10)
    swk3_id = models.CharField(max_length=3)
    l_kl3_rozk = models.CharField(max_length=40)
    l_kl2 = models.CharField(max_length=10)
    swk2_id = models.CharField(max_length=3)
    l_kl2_rozk = models.CharField(max_length=40)
    l_kl1 = models.CharField(max_length=10)
    swk1_id = models.CharField(max_length=3)
    l_kl1_rozk = models.CharField(max_length=40)
    l_klm = models.CharField(max_length=10)
    swkm_id = models.CharField(max_length=3)
    l_klm_rozk = models.CharField(max_length=40)
    st_id = models.CharField(max_length=19)
    tyn_id = models.CharField(max_length=3)
    l_z_pcw = models.CharField(max_length=1)
    l_stopien = models.CharField(max_length=2)
    l_2imie = models.CharField(max_length=15)
    l_imie_o = models.CharField(max_length=15)
    l_imie_m = models.CharField(max_length=15)
    l_ur = models.CharField(max_length=10)
    l_m_ur = models.CharField(max_length=20)
    l_nip = models.CharField(max_length=13)
    l_miasto = models.CharField(max_length=20)
    l_kod_p = models.CharField(max_length=6)
    l_ulica = models.CharField(max_length=30)
    l_fax = models.CharField(max_length=20)
    l_tel_s = models.CharField(max_length=40)
    l_tel_d = models.CharField(max_length=40)
    l_kat_zasz = models.CharField(max_length=2)
    l_wz = models.CharField(max_length=10)
    l_pzu = models.CharField(max_length=3)
    l_premia = models.CharField(max_length=3)
    l_pin = models.CharField(max_length=4)
    l_foto = models.CharField(max_length=70)
    l_podpis = models.CharField(max_length=70)
    l_opinia = models.CharField(max_length=255)
    l_pr_thn = models.CharField(max_length=4)
    l_pr_1 = models.CharField(max_length=1)
    l_pr_1od = models.CharField(max_length=2)
    l_pr_1odm = models.CharField(max_length=2)
    l_pr_1do = models.CharField(max_length=2)
    l_pr_1dom = models.CharField(max_length=2)
    l_pr_2 = models.CharField(max_length=1)
    l_pr_2od = models.CharField(max_length=2)
    l_pr_2odm = models.CharField(max_length=2)
    l_pr_2do = models.CharField(max_length=2)
    l_pr_2dom = models.CharField(max_length=2)
    l_pr_3 = models.CharField(max_length=1)
    l_pr_3od = models.CharField(max_length=2)
    l_pr_3odm = models.CharField(max_length=2)
    l_pr_3do = models.CharField(max_length=2)
    l_pr_3dom = models.CharField(max_length=2)
    l_pr_4 = models.CharField(max_length=1)
    l_pr_4od = models.CharField(max_length=2)
    l_pr_4odm = models.CharField(max_length=2)
    l_pr_4do = models.CharField(max_length=2)
    l_pr_4dom = models.CharField(max_length=2)
    l_pr_5 = models.CharField(max_length=1)
    l_pr_5od = models.CharField(max_length=2)
    l_pr_5odm = models.CharField(max_length=2)
    l_pr_5do = models.CharField(max_length=2)
    l_pr_5dom = models.CharField(max_length=2)
    l_pr_m = models.CharField(max_length=1)
    l_pr_mod = models.CharField(max_length=2)
    l_pr_modm = models.CharField(max_length=2)
    l_pr_mdo = models.CharField(max_length=2)
    l_pr_mdom = models.CharField(max_length=2)
    l_norma_p = models.CharField(max_length=4)
    l_status_p = models.CharField(max_length=1)
    l_pr_th = models.CharField(max_length=15)
    pr_id = models.CharField(max_length=10)

    #objects = DbfManager()

    class Meta:
        ordering=('l_nazw_im',)

class Pers_gr(models.Model):
    pers_st= models.ForeignKey('optylogis.Pers_st', on_delete=models.CASCADE)
    ium = models.CharField(max_length=6)
    nr_sw = models.CharField(max_length=12)
    data_nad = models.DateField()
    zaw = models.BooleanField()
    cof = models.BooleanField()
    ost_sp = models.DateField()

    #objects = DbfManager()

    class Meta:
        ordering=('pers_st__l_nazw_im',)